### ISSUE TITLE
Extra 40- in RTD Links

### ISSUE THREAD

**Issue by ColmBhandal** [canonical/sphinx-docs-guide#13]
There is a weird `40-` that doesn't seem like it should be there in these links:

[Read the Docs at Canonical](https://library.canonical.com/40-documentation/read-the-docs)

[How to publish documentation on Read the Docs](https://library.canonical.com/40-documentation/publish-on-read-the-docs)

**Comment by ru-fu** [comment]
Yes, those links have been changing quite a bit ... want to send a PR to fix them? ;)

**Comment by ColmBhandal** [comment]
Sure, I don't think I have write access here - would you be able to grant it to me? :)

**Comment by ru-fu** [comment]
You shouldn't need extra access to open a PR? Where are you getting stuck?

**Comment by ColmBhandal** [comment]
I'm getting stuck at the step "I'm too lazy to create a fork" :)

I'll create a fork I guess...

**Comment by ru-fu** [comment]
Yep, forks required. ;)
